package cmd

import (
	"fmt"
	"strings"

	"github.com/snip/internal/handler"
	"github.com/snip/internal/validation"
	"github.com/spf13/cobra"
)

var aiCreateTag string
var aiCreateContext string

func init() {
	aiCreateCmd.Flags().StringVarP(&aiCreateTag, "tag", "t", "", "Tag for the note")
	aiCreateCmd.Flags().StringVarP(&aiCreateContext, "context", "c", "", "Additional context for AI generation")
	rootCmd.AddCommand(aiCreateCmd)
}

var aiCreateCmd = &cobra.Command{
	Use:   "ai-create [topic]",
	Short: "Create a new note with AI-generated content",
	Long: `Create a new note with content generated by AI based on the topic.

The AI will generate well-structured and useful content about the topic.
You can provide additional context using the --context flag.

Examples:
  snip ai-create "Python Decorators"
  snip ai-create "Machine Learning Basics" --tag "learning"
  snip ai-create "REST API Design" --context "Focus on best practices" --tag "api"`,
	Args: cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if err := executeWithHandler(func(h handler.Handler) error {
			validator := validation.NewValidator()
			topic := strings.Join(args, " ")
			var tag *string
			if aiCreateTag != "" {
				tag = validator.CheckString(aiCreateTag)
			}
			context := ""
			if aiCreateContext != "" {
				context = aiCreateContext
			}
			return h.CreateNoteWithAI(topic, context, tag)
		}); err != nil {
			fmt.Printf("Error: %v\n", err)
		}
	},
}

